# Generated by Django 5.1 on 2024-08-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='created_from_application',
            field=models.BooleanField(default=False),
        ),
    ]
