# Generated by Django 5.1 on 2024-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_application_approved_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approved_entity',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
