# Generated by Django 5.1 on 2024-08-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_remove_application_approved_entity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='upvote',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('entity', 'ip_address')},
        ),
    ]
