# Generated by Django 5.1 on 2024-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_upvote_unique_together_upvote_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='upvote',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
