# Generated by Django 5.1 on 2024-08-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_visitorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
