# Generated by Django 5.1 on 2024-08-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_entity_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='entities.entitytype'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='entities.entitytype'),
        ),
    ]
